version: '3'
services:
  elasticsearch:
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security=false
      - xpack.monitoring.collection.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=p4ssw0rd
    image: "docker.elastic.co/elasticsearch/elasticsearch:${imageTag}"
    ports:
      - "9200:9200"
      - "9300:9300"
