---
SUITES:
  - suite: "helm"
    feature: "apm-server"
  - suite: "helm"
    feature: "filebeat"
  - suite: "helm"
    feature: "metricbeat"
  - suite: "ingest-manager"
    feature: "all"
  - suite: "metricbeat"
    feature: "apache"
  - suite: "metricbeat"
    feature: "metricbeat"
  - suite: "metricbeat"
    feature: "mysql"
  - suite: "metricbeat"
    feature: "redis"
  - suite: "metricbeat"
    feature: "vsphere"
