version: '3'
services:
  elasticsearch:
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=p4ssw0rd
    image: "docker.elastic.co/elasticsearch/elasticsearch:${stackVersion}"
    ports:
      - "9200:9200"
  kibana:
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=p4ssw0rd
    image: "docker.elastic.co/kibana/kibana:${stackVersion}"
    ports:
      - "5601:5601"
